services:
  postgres:
    image: 'postgres:17-alpine'
    container_name: 'postgres-container'
    environment:
      - 'POSTGRES_DB=user_sub_db'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
